// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportAudio(arg1, arg2) {
  return window['go']['main']['App']['ExportAudio'](arg1, arg2);
}

export function GenerateSpeech(arg1, arg2) {
  return window['go']['main']['App']['GenerateSpeech'](arg1, arg2);
}

export function GetPythonVenvPath() {
  return window['go']['main']['App']['GetPythonVenvPath']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SetPythonVenvPath(arg1) {
  return window['go']['main']['App']['SetPythonVenvPath'](arg1);
}
