// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportAudio(arg1:string,arg2:string):Promise<void>;

export function GenerateSpeech(arg1:string,arg2:string):Promise<string>;

export function GetPythonVenvPath():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function SetPythonVenvPath(arg1:string):Promise<void>;
